### ISSUE TITLE
Icon Bars not saving Positions 

### ISSUE THREAD

**Issue by Galthariel** [Dicebar/raven-old#17]
Hello,

 

I'll try to be the most concise as possible so you can understand the issue. The version I'm using is the one from Nov, 10th

 

1 - I have 4 Profiles and ALL have the same settings/configuration. Literally All

2 - Because I'm a new user and still learning everything about the addon, under Default, I only checked the Buffs and Debuffs. Unit Frame, Cast Bar, and Mirror are all unchecked

3 - Under Layout, I have checked only Icon Configuration. Bar Configuration is unchecked

4 - I have all 4 profiles with the position saved at Horizontal: 85.94 and Vertical: 96.53 and at every login or reload the Icon Bar moves to H: 98.29 and V:96.96

 

Let's say I'm using Profile A and after login, the Icon Bar is in the wrong position. I go to Profiles and I choose to copy from profile B the Icon Bars move to the right position.

Now I log into profile B (which is one I use to copy to fix profile A) and again the Icon Bars are in the wrong position. I then try to copy from profile C and it works...LOL

 

I think you now have a good idea about what's going on :-) Sorry for the long post and explanation but I think to fix is always good to have a good explanation about what's going on. Pls feel free to ask any questions

 

Thanks a lot for any help :-)

**Comment by Dicebar** [comment]
That's an interesting bug..

What resolution are you playing on?

**Comment by Galthariel** [comment]
2560x1440

When I was using the version from Nov, 9th was happening like at every login almost. Now with the version from Nov, 10th it seems that isn't happening...I'll do a lot of tests today logging in different characters and let you know. Bear with me please :-)

**Comment by Dicebar** [comment]
Oh, that's actually great to hear!

That means either we fixed something... Or something in Blizzard's UI was causing problems and they fixed that themselves. And I suspect the latter; I was seeing quite a few Edit Mode related errors yesterday that seem to have all but disappeared for me today.

**Comment by Galthariel** [comment]
Yep...and like I said I'll do more tests today to be really sure and if doesn't happen again I'll close the Issue myself. Thanks a to for your support and attention :-)

**Comment by Dicebar** [comment]
Thank you for the excellent tests and making our job easier 😉

**Comment by Galthariel** [comment]
Just happen again out of Blue...check these screenshots

Original Position



![2022-11-11_18-46-41](https://user-images.githubusercontent.com/51491805/201435568-be516cc1-82d0-4683-8a26-c4ebab64e101.png)

and then suddenly moved to the top right corner


![2022-11-11_18-45-49](https://user-images.githubusercontent.com/51491805/201435635-cb446291-b543-4cdb-ac7f-aef78879ee31.png)

and happened when I left ZM (got the loading screen) and then when I show up in Oribos was like that. It's indeed a weird bug. The other thing I noticed is some settings that I have checked show unchecked when that happens.

**Comment by Galthariel** [comment]
As I said...not a big issue because I just go to Profiles and copy Profile B to Profile A (the one that the issue just happened) and get it fixed. What is bugging me is that I then log in with the toon that has Profile B (was right and I even used to fix A) and now it's wrong...super weird. I think is something related to the whole settings not being kept by some reason but I'm not a Dev and just trying to give as much information as I can :-)

Hope that helps

**Comment by dorana** [comment]
I myself had position issue with Raven in Shadowlands. where one particular group sometimes shifted 400px left from it's set position.
However I think my issue was due to another addon that shifts the pixels coordinates to move the center point of the camera.

We'll look into this, it might not have been the issue I thought.
Very strange and interesting

**Comment by Galthariel** [comment]
Confirmed. Happens (not always but when it happens) when I go through a loading screen which can be when I log into the game, reload, use a Portal, or move from one area to another that requires a loading screen (e.g get into an instance)

**Comment by Dicebar** [comment]
And now for the hardest test... Does this bug also happen when Raven is the only addon enabled?

**Comment by Dicebar** [comment]
We've moved repositories as we're now doing the official releases through CurseForge. I've recreated this ticket [here](https://github.com/Dicebar/Raven/issues/3). Please use that issue for future correspondence, thanks!
